# Choosing the right visualization software

**Learning objectives:**

- Identify some considerations for which visualization software is right for you

## Choosing the right visualization software {-}

- Using the tool you know _may_ be best 

- Learning new tools entails a learning curve 

- There's always a pull to learn the latest tool

## Reproducibility and repeatability {-}

- Favour tools that allow for repeatability 

- Reproducibility
  - Are the data available? 
  - Are transformations specified? 

- Repeatability 
  - Identical down to the pixel

## Data exploration versus data presentation {-}

- Favour tools that allow for fast and easy exploration 

- Favour tools that allow for repeatable presentation 

- If you need to manually modify a graphic for presentation, do so without reservation, but be aware that recreating the visual will be harder. 

## Separation of content and design {-}

- Favour tools that separate content and design

- Content and design require different skills

- Tools that separate content from design are easier to incrementally tweak 